### ISSUE TITLE
AutoStack- move minecraft logging to a seperate file compared to mineShell logging

### ISSUE THREAD

**Issue by carlquistb** [carlquistb/FormulaCraft#38]
currently, all output from the service is logged to stdout, which can be accessed by ```journalctl -u mineService```

It would be better is the output straight from the game is logged to a separate file, so that we can more easily look for our mineService debugging output in journalctl.

Question: if stdout for the child process is piped to a file, what is the lag time for availability in that file?

**Comment by nlipiarski** [comment]
Closed by PR #39
